services:
  - type: web
    name: mauling-simulator
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
    plan: free
    autoDeploy: true
    healthCheckPath: /
    disk:
      name: mauling-data
      mountPath: /data
      sizeGB: 1
    domains:
      - mauling-simulator.onrender.com

